# Generated by Django 3.0.7 on 2020-06-15 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adrerss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('line_one', models.CharField(max_length=50)),
                ('line_two', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'adrerss',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adrerss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Adrerss')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Client')),
            ],
            options={
                'db_table': 'client_order',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('lenguaje', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Disccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_name', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disccount',
            },
        ),
        migrations.CreateModel(
            name='PrimeSuscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vality_type', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prime_suscription',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Brand')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.City')),
            ],
            options={
                'db_table': 'retailer',
            },
        ),
        migrations.CreateModel(
            name='ShoopingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shooping_car',
            },
        ),
        migrations.CreateModel(
            name='Subcategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Categorie')),
            ],
            options={
                'db_table': 'subcategorie',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Categorie')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Retailer')),
            ],
            options={
                'db_table': 'stock_item',
                'unique_together': {('retailer', 'product')},
            },
        ),
        migrations.CreateModel(
            name='ShoopingCarItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('note_for_shopper', models.TextField()),
                ('shooping_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.ShoopingCar')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.StockItem')),
            ],
            options={
                'db_table': 'shooping_car_items',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.City')),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='RetailerCoverageSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Retailer')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Sector')),
            ],
            options={
                'db_table': 'retailer_coverage_sector',
            },
        ),
        migrations.CreateModel(
            name='RetailerCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Categorie')),
            ],
            options={
                'db_table': 'retailer_categories',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Country')),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('note_for_shopper', models.TextField()),
                ('pvp_with_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.ClientOrder')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.StockItem')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='ClientShoopingCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('menbers', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Client')),
            ],
            options={
                'db_table': 'client_shooping_car',
            },
        ),
        migrations.CreateModel(
            name='ClientPrimeSuscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateField()),
                ('suscription_state', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Client')),
                ('prime_suscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.PrimeSuscription')),
            ],
            options={
                'db_table': 'client_prime_suscription',
            },
        ),
        migrations.AddField(
            model_name='clientorder',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Retailer'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Province'),
        ),
        migrations.AddField(
            model_name='adrerss',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motor_descuento.Sector'),
        ),
    ]
