# Generated by Django 3.0.7 on 2020-06-16 22:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_descuento', '0003_disccount_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='disccount',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='disccount',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
